
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ProjectName-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ProjectName
  template:
    metadata:
      labels:
        app: ProjectName
    spec:
      containers:
      - name: projectnamelowercase
        image: abc.azurecr.io/imagename:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: keyname

---
apiVersion: v1
kind: Service
metadata:
  name: projectnamelowercase
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ProjectName